import type { Metadata } from "next";
import Image from "next/image";
import { ArrowRight, CircleAlert, FlaskConical, Microscope, Scale, ShieldCheck } from "lucide-react";
import { PageHero } from "../components/PageHero";
import { HairCycleExplorer } from "../components/HairCycleExplorer";
import { ThemeLink as Link } from "../components/ThemeLink";

export const metadata: Metadata = { title: "Hair Science | Inruuts", description: "Learn how follicles grow, what DHT does, why shedding happens and how evidence should shape personalized hair care." };

export default function SciencePage() {
  return <main className="science-page">
    <PageHero eyebrow="The science" title="Hair biology, explained without turning it into a sales trick." copy="Explore the growth cycle, follicle miniaturization, DHT, scalp health, nutrition and the evidence boundaries that shape a responsible personalized plan." image="/assets/science-hero.jpg" alt="Magnified examination of human hair and scalp" cta="Build my hair profile" note="Reviewed sources · Plain-language limits" />

    <section className="section anatomy-section"><div className="section-title"><p className="kicker">Start with the follicle</p><h2>A hair fiber is the visible output of a living mini-organ.</h2><p>The shaft above the skin is made of keratinized cells. Growth activity happens below the surface, where the follicle cycles, receives signals and produces a new fiber.</p></div><div className="anatomy-grid"><article><div className="anatomy-image"><Image src="/assets/follicle-healthy.jpg" alt="Illustration of a healthy growing hair follicle" fill sizes="(max-width: 800px) 100vw, 50vw" /></div><span>Healthy terminal follicle</span><h3>Long growth, thicker fiber</h3><p>A longer anagen phase allows a terminal scalp hair to grow longer and thicker before transition and rest.</p></article><article><div className="anatomy-image"><Image src="/assets/follicle-miniaturized.jpg" alt="Illustration of a miniaturized hair follicle" fill sizes="(max-width: 800px) 100vw, 50vw" /></div><span>Miniaturizing follicle</span><h3>Shorter cycle, finer fiber</h3><p>In androgenetic alopecia, susceptible follicles can progressively produce shorter, finer hairs over repeated cycles.</p></article></div></section>

    <section className="cycle-band" id="cycle"><div className="section-title left"><p className="kicker">The growth cycle</p><h2>Growth and shedding are parts of the same system.</h2><p>Click each phase to see why hair changes need time to observe.</p></div><HairCycleExplorer /></section>

    <section className="section dht-section" id="dht"><div className="dht-copy"><p className="kicker">DHT + pattern loss</p><h2>Genes determine which scalp follicles are sensitive.</h2><p>5-alpha-reductase converts testosterone to dihydrotestosterone, or DHT. DHT binds androgen receptors throughout the body, but in genetically susceptible scalp follicles it can contribute to miniaturization and a shorter growth phase. That is why pattern loss follows recognizable scalp regions rather than affecting every hair equally.</p><div className="evidence-callout"><Scale size={22} /><div><b>Important distinction</b><p>DHT is a normal hormone. The issue in pattern hair loss is follicle sensitivity and signaling, not simply having “too much testosterone.”</p></div></div></div><div className="dht-image"><Image src="/assets/dht-mechanism.jpg" alt="Illustration of testosterone conversion, DHT signaling and follicle miniaturization" fill sizes="(max-width: 800px) 100vw, 50vw" /></div></section>

    <section className="factor-band"><div className="section-title"><p className="kicker">Contributing-factor map</p><h2>“Hair loss” is an outcome, not one diagnosis.</h2></div><div className="factor-grid"><article><span>Genes + androgens</span><p>Gradual patterned miniaturization in susceptible follicles.</p></article><article><span>Cycle disruption</span><p>Illness, birth, surgery, rapid weight change or major stress can shift more hairs toward shedding.</p></article><article><span>Immune activity</span><p>Alopecia areata can cause sudden smooth patches and requires medical assessment.</p></article><article><span>Scalp disease</span><p>Inflammation, infection and scarring conditions can affect follicles.</p></article><article><span>Fiber damage</span><p>Heat, bleach, friction and tension can reduce visible length and density through breakage.</p></article><article><span>Nutrition + health</span><p>Deficiencies, thyroid disease, medications and other health factors may contribute in some people.</p></article></div></section>

    <section className="split-band split-band-coral" id="scalp"><div className="split-media"><Image src="/assets/scalp-barrier.jpg" alt="Illustration of a balanced scalp barrier and an area with buildup and flaking" fill sizes="(max-width: 800px) 100vw, 50vw" /></div><div className="split-copy"><p className="kicker">The scalp environment</p><h2>Scalp care can support comfort. It cannot diagnose the cause of loss.</h2><p>Cleansing can remove oil, sweat, styling residue and loose scale. Conditioning can reduce friction on fibers. Persistent itching, burning, thick scale, pustules or scarring need medical evaluation rather than stronger cosmetic products.</p></div></section>

    <section className="section nutrition-section" id="nutrition"><div className="section-title left"><p className="kicker">Nutrition + hair</p><h2>Correct the gap, not the marketing fantasy.</h2></div><div className="nutrition-layout"><div className="nutrition-image"><Image src="/assets/nutrient-pathway.jpg" alt="Illustration of nutrients and oxygen reaching a hair follicle" fill sizes="(max-width: 800px) 100vw, 52vw" /></div><div className="nutrition-copy"><p>Normal hair production depends on adequate energy, protein and micronutrients. But visible loss does not prove a deficiency, and excess supplementation does not create unlimited growth.</p><ul className="check-list"><li><ShieldCheck size={17} /> Use history and symptoms to guide testing</li><li><ShieldCheck size={17} /> Review iron, vitamin D or thyroid concerns with a clinician</li><li><ShieldCheck size={17} /> Check medications and supplement interactions</li><li><ShieldCheck size={17} /> Avoid high-dose “more is better” thinking</li></ul></div></div></section>

    <section className="evidence-band"><div className="section-title left"><p className="kicker">Evidence ladder</p><h2>Not every “science-backed” statement means the same thing.</h2></div><div className="evidence-grid"><article><Microscope size={24} /><span>Level 1</span><h3>Finished-product clinical study</h3><p>The strongest match when the tested formula, population, dose and outcome align with the claim.</p></article><article><FlaskConical size={24} /><span>Level 2</span><h3>Ingredient-level evidence</h3><p>Useful context, but it does not automatically prove the final blend works the same way.</p></article><article><Scale size={24} /><span>Level 3</span><h3>Instrumental cosmetic testing</h3><p>Can support fiber strength, breakage, shine or hydration claims when methods are clear.</p></article><article><ShieldCheck size={24} /><span>Level 4</span><h3>Customer perception</h3><p>Surveys and testimonials describe experiences; they do not replace controlled evidence.</p></article></div><div className="lab-image"><Image src="/assets/lab-ingredients.jpg" alt="Cosmetic formulation laboratory with dropper, molecular model and botanical ingredients" fill sizes="100vw" /></div></section>

    <section className="personalization-band"><div className="personalization-image"><Image src="/assets/personalization-system.jpg" alt="Illustration of inputs feeding a personalized hair-care recommendation" fill sizes="(max-width: 800px) 100vw, 50vw" /></div><div><p className="kicker">How Inruuts uses the science</p><h2>Finite rules. Visible reasoning. Clear limits.</h2><ol><li><span>01</span><p>Classify the concern and pattern the user reports.</p></li><li><span>02</span><p>Check timing, symptoms and red flags before recommending products.</p></li><li><span>03</span><p>Match cosmetic categories to scalp, fiber and routine needs.</p></li><li><span>04</span><p>Show why each item was selected and what it cannot do.</p></li></ol><Link className="primary-button" href="/quiz">Build my profile <ArrowRight size={17} /></Link></div></section>

    <section className="red-flag-band" id="red-flags"><CircleAlert size={30} /><div><p className="kicker">When Inruuts is not enough</p><h2>Sudden, patchy, painful, inflamed, scarring or rapidly progressing loss.</h2><p>These signs may need physical examination, medical history, laboratory testing or prescription treatment. An online cosmetic profile should route away from a sale.</p></div><Link className="secondary-button" href="/quiz">Check my profile <ArrowRight size={17} /></Link></section>

    <section className="source-section"><div><h2>Source baseline</h2><p>Educational content is grounded in U.S. dermatology guidance and peer-reviewed reviews. Final published medical copy still requires professional review.</p></div><div className="source-links"><a href="https://www.aad.org/public/diseases/hair-loss/causes/18-causes" target="_blank" rel="noreferrer">American Academy of Dermatology <ArrowRight size={15} /></a><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC10932098/" target="_blank" rel="noreferrer">NIH/PMC follicle biology review <ArrowRight size={15} /></a><a href="https://www.mayoclinic.org/diseases-conditions/hair-loss/symptoms-causes/syc-20372926" target="_blank" rel="noreferrer">Mayo Clinic overview <ArrowRight size={15} /></a></div></section>
  </main>;
}
